GET http://localhost:5001/calendar/all

###

GET http://localhost:5001/calendar/all?from=2021-05-22T13:00:00.000Z&to=2021-05-23T23:00:00.000Z

###

GET http://localhost:5001/calendar/all?to=2021-05-23T13:00:00.000Z

###

GET http://localhost:5001/calendar/all

###

POST http://localhost:5001/calendar/event
content-type: application/json

{
	"title": "Event11",
	"startTime": "2021-05-27T21:30:39.000Z",
    "endTime": "2021-05-27T22:30:39.000Z",
    "recur": "false",
	"description": "My tenth event"
}

###

PUT http://localhost:5001/calendar/event/update/60aa5d68ecddb43106b211c3
content-type: application/json

{
	"title": "Event10_udpated",
	"startTime": "2021-05-27T13:00:00.000Z",
	"description": "My tenth event"
}

